#!/usr/bin/env node --harmony --harmony_arrow_functions --harmony_modules

import program from 'commander'
import cliff from 'cliff'
import Story from './story'

program
  .option('-p, --project-id [projectId]', 'project id')
  .option('-t, --token [token]', 'token')
  .parse(process.argv)

Story.set({ projectId: program.projectId, token: program.token })
Story.getList()
  .then((stories) => {
    let formattedStories = stories.map((story) => {
      return [story.id, story.estimate, story.name]
    })

    console.log(cliff.stringifyRows(formattedStories));
  }).catch(function(err) {
    console.error(colors.red("error: " + err.data.general_problem))
  })
