#!/usr/bin/env node --harmony --harmony_arrow_functions --harmony_modules

import program from 'commander'
import cliff from 'cliff'
import Pvt from 'pvt'

program
  .option('-p, --project-id [projectId]', 'project id')
  .option('-t, --token [token]', 'token')
  .option('-s, --state [state]', 'filter by state')
  .parse(process.argv)

Pvt.Story.set({ projectId: program.projectId, token: program.token })

let parameters = {}
if (program.state) parameters.with_state = program.state

Pvt.Story.getList(parameters)
  .then((stories) => {
    let formattedStories = stories.map((story) => {
      return [story.id, story.estimate, story.name]
    })

    console.log(cliff.stringifyRows(formattedStories));
  }).catch(function(err) {
    console.error(colors.red("error: " + err.data.general_problem))
  })
