#!/usr/bin/env node --harmony --harmony_arrow_functions --harmony_modules

import program from 'commander'
import cliff from 'cliff'
import Pvt from 'pvt'
import colors from 'colors'

program
  .option('-p, --project-id [projectId]', 'project id')
  .option('-t, --token [token]', 'token')
  .option('-s, --state [state]', 'filter by state')
  .parse(process.argv)

Pvt.Story.setMetaInfo({
  projectId: program.projectId || process.env.PIVOTAL_TRACKER_DEFAULT_PROJECT_ID,
  token: program.token || process.env.PIVOTAL_TRACKER_TOKEN
})

let parameters = {}
if (program.state) parameters.with_state = program.state

Pvt.Story.getList(parameters)
  .then((stories) => {
    let formattedStories = stories.map((story) => {
      return [story.id, story.estimate, story.current_state, story.name]
    })
    console.log(cliff.stringifyRows(formattedStories));
  }).catch(function(err) {
    console.log(err);
    // console.error(colors.red("error: " + err.data.general_problem))
  })
