#!/usr/bin/env node --harmony --harmony_arrow_functions --harmony_modules

import program from 'commander'
import cliff from 'cliff'
import Pvt from 'pvt'
import colors from 'colors'

program
  .option('-p, --project-id [projectId]', 'project id')
  .option('-t, --token [token]', 'token')
  .option('-l, --labels [labels]', 'add labels')
  .parse(process.argv)

Pvt.Story.setMetaInfo({
  projectId: program.projectId || process.env.PIVOTAL_TRACKER_DEFAULT_PROJECT_ID,
  token: program.token || process.env.PIVOTAL_TRACKER_TOKEN
})

let parameters = {}
if (program.state) parameters.with_state = program.state

Pvt.Story.save({
  name: program.args[0],
  estimate: program.args[1],
  story_type: program.args[2],
  current_state: program.args[3],
  labels: program.labels.split(','),
}).then((story) => {
  let formattedStory = [[
    story.id,
    story.estimate,
    story.current_state,
    story.name,
  ]]
  console.log(cliff.stringifyRows(formattedStory));
}).catch(function(err) {
  console.error(err);
})
